[imaging_specs]
local_storage_directory = "C:\\diSPIM_test"
subject_id = "test"
tile_prefix = "dispim_test"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 15
z_step_size_um = 0.209
volume_x_um = 800.0
volume_y_um = 400.0
volume_z_um = 1000
laser_wavelengths = [ 488,]
camera_streams = [ 0,]
external_storage_directory = "C:\\diSPIM_test"
filetype = "Tiff"
acquisition_style = "interleaved"

[experiment_specs]
experimenters_name = "Micah Woodard"
immersion_medium = "1xPBS"
immersion_medium_refractive_index = 1.33

[tile_specs]
x_field_of_view_um = 686.592
y_field_of_view_um = 686.592
row_count_pixels = 2304
column_count_pixels = 2304
data_type = "uint16"

[camera_specs.hamamatsu]
driver = "ispim.devices.camera"
module = "Camera"

[camera_specs.hamamatsu.kwds]
name = "Hamamatsu C15440-20UP S/N: 500749"

[camera_specs.hamamatsu.configure]
tile_shape = [2304, 2304]
scan_direction = "BACKWARD"
exposure_time_ms = 0.025
slit_width_px = 150


[channel_specs.main.kwds]
port = "COM3"

[channel_specs.405]
driver = "oxxius_laser"
module = "OxxiusLaser"
intensity_mode = "current"
color = "purple"
filter_index = 1
ao_channel = 12
disable_voltage = 0.0
enable_voltage = 5.0

[channel_specs.405.etl]
offset = 2.823
amplitude = 0

[channel_specs.405.galvo]
x_offset = 2.21
x_amplitude = -0.01
y_offset = 2.343
y_amplitude = 1.259

[channel_specs.405.kwds]
prefix = "L6"
intensity_mode = "current"
modulation_mode = "DigitalModulation"
laser_driver_control_mode = "current"
external_control = false
